### ISSUE TITLE
syntax error with Python2

### ISSUE THREAD

**Issue by bahatiphill** [Aleksander-Drozd/csvwlib#1]
when i tried to import  "**CSVWConverter**", here comes syntax error on  "**ModelConverter.py**" file 

here' a syntax error on line 59 
`tables[-1] = {**table_metadata['tableSchema'], **tables[-1]}`

**Comment by Aleksander-Drozd** [comment]
_csvwlib_ is not compatible with Python 2. I will add a note to readme about this.
