### ISSUE TITLE
Ongoing  maintenance for library + PyPi package

### ISSUE THREAD

**Issue by ceteri** [Aleksander-Drozd/csvwlib#5]
Hi @Aleksander-Drozd,

We'd be happy to continue ongoing maintenance for `csvwlib` and package support on PyPi.  This is really useful, and much more succinct than other alternative CSVW implementations we've evaluated. FWIW, we're integrating use of `csvwlib` into the `kglab` project and related training courses, book project, etc.

I've forked the repo. If it would be appropriate to add me on the PyPi release, then I could keep continuity there https://pypi.org/project/csvwlib/

> This package is no longer maintained. Feel free to fork and develop on your own

Many thanks,
Paco

**Comment by Aleksander-Drozd** [comment]
Invitation sent

**Comment by ceteri** [comment]
Thank you @Aleksander-Drozd
